version: "3.7"
#este arquivo precisa ser identado

services:
    app: #nome do serviço que vai orquestrar o que fizemos no dockerfile
      build: .  #seria a mesma coisa que executar na mao o 'docker build -t rentx .'
      container_name: rentx
      ports:
        - 3333:3333
      volumes: #nosso workdir
        - .:/usr/app  #pega do diretorio atual e envia para /usr/app  (origem:destino)
      
